name: Angular CI

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main, testing ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Create Angular environment files
      run: |
        mkdir -p src/environments
        echo "export const environment = { production: false, apiUrl: '${{ secrets.API_URL_DEV }}' };" > src/environments/environment.development.ts
        echo "export const environment = { production: true, apiUrl: '${{ secrets.API_URL_PROD }}' };" > src/environments/environment.ts

    - name: Build
      run: npm run build --if-present
    
    - name: Run tests
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless